import { Open_Sans } from "next/font/google";

import "./globals.css";

import AuthProvider from "./AuthProvider";
import NavMenu from "@/app/NavMenu";

const myFont = Open_Sans({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={myFont.className}>
          <div className="container">
            <NavMenu />
            <main>{children}</main>

            <footer>
              <p>
                Created for the{" "}
                <a href="https://fireship.io">
                  Fireship Next.js 13 Full Course
                </a>
              </p>
            </footer>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
